baseurl: /undp-projects
prose:
  rooturl: "_posts"
  media: "undp-projects/media"
  metadata:
    _posts/donors:
      - name: "category"
        field:
          element: "hidden"
          value: "donor"
    _posts/about:
      - name: "category"
        field:
          element: "hidden"
          value: "about"